### ISSUE TITLE
Font Generation Question

### ISSUE THREAD

**Issue by agieocean** [Pastisha/EDOPRO-Skinpack#1]
Trying to modify the font for some of the themes and I'm wondering how to generate the proper file for this.
For reference the font file I'm trying to generate is one to replace this file:
[fontTahoma.png](https://github.com/Lahrenheit/EDOPRO-Skinpack/blob/master/Kaiba%20The%20Revenge/fontTahoma.png)

**Comment by Lahrenheit** [comment]
Hello RenFinkle, the font that the game use is stored in "fonts" folder of edropro (or ygopro base related game).
For change the font you should edit the "sytem.conf" file, it is stored in "config/system.conf" (edopro) in the lines:

(for example, in my game:)

textfont = fonts/NotoSansJP-Regular.otf 12
numfont = fonts/numfont.ttf

Here you can change the font, saving the font in "fonts" folder, but watch out that not all fonts will be fit in edopro

P.S: the "fonttahoma.png" was used in earlier versions of ygopro skins, I don't delete it because it perhaps will be useful in sometime, cheers!

**Comment by agieocean** [comment]
Thanks so much!
